on:
  workflow_dispatch:

# https://docs.github.com/en/actions/deployment/security-hardening-your-deployments/about-security-hardening-with-openid-connect

env:
  TOKEN_URL: https://7681-84-214-35-96.eu.ngrok.io/token

jobs:
  test-token:
    # Enable token usage
    permissions:
      id-token: write
    runs-on: ubuntu-latest
    steps:
      - run: |
          echo "Getting token from Github"
          TOKEN=$(curl -H "Authorization: bearer $ACTIONS_ID_TOKEN_REQUEST_TOKEN" "$ACTIONS_ID_TOKEN_REQUEST_URL" | jq -r '.value')
          echo "Signing in using token"
          curl -H "X-Token: $TOKEN" "$TOKEN_URL"
          echo "Done"
